apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: zenithworksmygoapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zenithworksmygoapp 
    spec:
      containers:
        - name: zenithworksmygoapp 
          image: raireg1.azurecr.io/zenithworksmygoapp
          ports:
          - containerPort: 80